networks:
  database:
volumes:
  database:
services:
  backend:
    image: educationmanagementsystem
    build:
      context: .
      dockerfile: EducationManagementSystem/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 6050:8080
    networks:
      - database
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - database
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - database
    depends_on:
      - database