networks:
  database:
volumes:
  database:
  nginx:
services:
  backend:
    image: educationmanagementsystem
    build:
      context: .
      dockerfile: EducationManagementSystem/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 3000:8080
    networks:
      - database
  database:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB}, ${KEYCLOAK_DB}
    networks:
      - database
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://database/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
    ports:
      - 4000:8080
    networks:
      - database
    command: start-dev --log-level=DEBUG
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - database
  nginx:
    image: nginx
    restart: always
    volumes:
      - nginx:/etc/nginx/nginx
    ports:
      - 8000:80